routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('test',function(){
	factory(App\AlumniPhoto::class, 20)->create();
});


Route::get('/gallery','Frontend\GalleryController@gallery');
Route::get('/gallery/getmorealbums','Frontend\GalleryController@getmorealbums')->name('albums.getmore');

Route::get('/gallery/{slug}/getmoreimages','Frontend\GalleryController@getmoreimages')->name('images.getmore');
Route::get('/gallery/{category}/{slug}','Frontend\GalleryController@images')->name('frontend.album');

Route::get('calendar','Frontend\HomeController@calender')->name('calender');

Route::post('contact_us', 'Frontend\HomeController@contact_us')->name('contact_us');
Route::post('feedback', 'Frontend\HomeController@feedback');
Route::post('subscribe', 'Frontend\HomeController@subscribe');
Route::get('unsubscribe/{token}', 'Frontend\HomeController@unsubscribe')->name('unsubscribe');
Route::post('unsubscribe/{token}', 'Frontend\HomeController@unsubscribed')->name('unsubscribed');

Route::prefix('alumni')->group(function(){
	Route::post('/login','Frontend\Alumni\Auth\LoginController@login')->name('alumni_login');
	Route::post('/logout','Frontend\Alumni\Auth\LoginController@logout')->name('alumni_logout');
	Route::post('/register','Frontend\Alumni\Auth\RegisterController@register')->name('alumni_register');
	Route::post('/password/email','Frontend\Alumni\Auth\ForgotPasswordController@sendResetLinkEmail')->name('alumni_password.email');
	Route::post('/password/reset','Frontend\Alumni\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Frontend\Alumni\Auth\ForgotPasswordController@showLinkRequestForm')->name('alumni_password.request');
	Route::get('/password/reset/{token}','Frontend\Alumni\Auth\ResetPasswordController@showResetForm')->name('alumni_password.reset');
	
	Route::get('gallery','Frontend\Alumni\AlumniController@gallery')->name('alumni.gallery');
	Route::get('/gallery/filterBatch','Frontend\Alumni\AlumniController@filterBatch')->name('alumni_photos.filterBatch');

	Route::get('/post/{slug}','Frontend\Alumni\AlumniController@singlePost')->name('alumni.singlepost');
	Route::post('post/{id}/comment','Frontend\Alumni\AlumniController@comment')->name('post.comment');
	Route::post('post/{post_id}/getmorecomments','Frontend\Alumni\AlumniController@getMoreComments')->name('post.getmorecomments');
	
	Route::get('blog','Frontend\Alumni\AlumniController@index')->name('alumni.blog');
	Route::get('blog/getmoreposts','Frontend\Alumni\AlumniController@getMorePosts')->name('alumni.blog.getmoreposts');

	Route::get('myposts','Frontend\Alumni\AlumniController@myposts')->name('alumni.myposts');
	Route::get('myposts/getmoreposts','Frontend\Alumni\AlumniController@getMoreMyPosts')->name('alumni.myposts.getmoreposts');
	Route::post('myposts/add','Frontend\Alumni\AlumniController@addPost')->name('alumni.myposts.add');
	Route::post('myposts/{id}/edit','Frontend\Alumni\AlumniController@editPost')->name('alumni.myposts.edit');
	Route::post('myposts/{id}/delete','Frontend\Alumni\AlumniController@deletePost')->name('alumni.myposts.delete');

	Route::get('/','Frontend\Alumni\AlumniController@index')->name('alumni');
});

Route::get('changepassword','AdminUserController@changepassword')->name('admin.changepassword');
Route::post('changedpassword','AdminUserController@changedpassword')->name('admin.changedpassword');

Route::prefix('admin')->group(function(){
	Auth::routes();
	Route::get('dashboard','Admin\AdminController@index')->name('dashboard');

	Route::get('staffs','Admin\StaffController@index')->name('staffs.index');
    Route::post('staffs/update','Admin\StaffController@update')->name('staffs.update');    
    Route::post('staffs/delete/{id}','Admin\StaffController@destroy')->name('staffs.destroy');
    Route::post('verifyPassword','Admin\StaffController@verifyPassword')->name('verifyPassword');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

	Route::get('notice','NoticeController@index');
	Route::get('notice/search','NoticeController@search');
	Route::get('notice/create','NoticeController@create');
	Route::post('notice/create','NoticeController@store');
	Route::post('notice/changeStatus','NoticeController@changeStatus');
	Route::get('/notice/{notice}/edit','NoticeController@edit');
	Route::post('/notice/{notice}/update','NoticeController@update');
	Route::post('/notice/delete','NoticeController@destroy');

	Route::resource('/resources', 'ResourcesController');
	Route::post('/resources/update','ResourcesController@update');
	Route::post('/resources/delete','ResourcesController@destroy');

	//Route::resource('/materials', 'MaterialsController');
	Route::get('materials/create','ResourcesController@matcreate');
	Route::get('materials/{material}/edit','ResourcesController@matedit');
	Route::get('materials/{material}/matshow','ResourcesController@matshow');
	Route::post('materials/create','ResourcesController@matstore');
	Route::post('/materials/update','ResourcesController@matupdate');
	Route::post('/materials/delete','ResourcesController@matdestroy');
	Route::post('materials/matchangeStatus','ResourcesController@matchangeStatus');

	Route::post('/gallery/{album_id}/imageStore','GalleryController@imageStore')->name('gallery.addImages');
	Route::delete('/gallery/{album_id}/imageDelete/{image_id}','GalleryController@imageDelete')->name('gallery.deleteImage');
	Route::resource('gallery',"GalleryController",['except' => ['create','edit']]);	

	//downloads
	Route::get('/downloads','DownloadsController@index')->name('downloads.index');
	Route::post('/downloads','DownloadsController@store')->name('downloads.store');
	Route::post('/downloads/delete','DownloadsController@destroy')->name('downloads.destroy');
	Route::get('/downloads/search','DownloadsController@search');
	Route::post('/downloads/update','DownloadsController@update')->name('downloads.update');

	///news
	// Route::get('/news','NewsController@index')->name('admin.news');
	// Route::post('news','NewsController@store')->name('news.store');
	// Route::post('news/delete','NewsController@destroy')->name('news.delete');
	// Route::get('news/{id}/edit','NewsController@edit')->name('news.edit');
	// Route::post('news/update','NewsController@update')->name('news.update');
	// Route::get('news/{id}/view','NewsController@show')->name('news.show');

	//testimonials
	Route::get('/testimonials','TestimonialsController@index')->name('admin.testimonials');
	Route::post('/testimonials','TestimonialsController@store')->name('testimonials.store');
	Route::post('testimonials/delete','TestimonialsController@destroy')->name('testimonials.destroy');
	Route::get('/testimonials/{id}/edit','TestimonialsController@edit')->name('testimonials.edit');
	Route::post('testimonials/update','TestimonialsController@update')->name('testimonials.update');
	
	//sliderimage backend
	// Route::get('slider','SliderImageController@index')->name('admin.slider');
	// Route::post('slider','SliderImageController@store')->name('slider.store');
	// Route::post('slider/delete','SliderImageController@destroy')->name('slider.destroy');
	// Route::post('slider/update','SliderImageController@update')->name('slider.update');

	//Teachers configuration 
	Route::get('teachers','TeacherController@index')->name('admin.teachers');
	Route::post('teachers','TeacherController@store')->name('teachers.store');
	Route::get('teachers/{id}/edit','TeacherController@edit')->name('teachers.edit');
	Route::post('teachers/update','TeacherController@update')->name('teachers.update');
	Route::post('teachers/delete','TeacherController@destroy')->name('teachers.destroy');

	//downloadscategory routes
	Route::post('downloadscategory','DownloadsController@storeCat')->name('downloadscategory.store');
	Route::post('downloadscategory/update','DownloadsController@updatecat')->name('downloadscategory.update');
	Route::post('downloadscategory/delete','DownloadsController@deletecat')->name('downloadscategory.delete');


	//events routes
	Route::get('events','EventController@index')->name('admin.events');
	Route::post('events','EventController@store')->name('events.store');
	Route::post('events/delete','EventController@destroy')->name('events.destroy');
	Route::get('events/{id}/edit','EventController@edit')->name('events.edit');
	Route::post('events/update','EventController@update')->name('events.update');
	Route::get('events/{id}/view','EventController@view')->name('events.view');
	Route::get('events/{id}/images','EventController@images')->name('events.images.index');
	Route::post('events/{id}/images/upload','EventController@UploadImages')->name('events.images.upload');
	Route::delete('events/{event_id}/images/{image_id}','EventController@imageDelete')->name('events.images.delete');

	Route::resource('calender', 'Admin\EventCalenderController');

	Route::get('contact-us-messages/unseen','Admin\ContactController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::resource('contact-us-messages', 'Admin\ContactController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactController@getUnseenMsg')->name('getUnseenMsg');

    Route::get('feedbacks/unseen','Admin\FeedbackController@unseenMsg')->name('feedbacks.unseen');  

resources/views/admin/partials/anotis.blade.php
@if($ano == 0)
    <p class="notification-text font-small-3 text-muted text-xs-center" style="margin:20px">No new requests</p>
@endif
@foreach($alreqs as $f)
    <?php 
        $interval = \Carbon\Carbon::createFromTimeStamp(strtotime($f->created_at))->diffForHumans();
    ?>
    <a href="{{ route('alumni_requests.show',$f->id) }}" class="list-group-item">
    <div class="media">
        <div class="media-left"><span class="avatar avatar-sm avatar-online rounded-circle"><img src="{{ asset('alumni_pp/'.$f->photo) }}" alt="avatar"><i></i></span></div>
        <div class="media-body">
        <h6 class="media-heading">{{ $f->name }}</h6>
        <p class="notification-text font-small-3 text-muted" style="line-height:1.2em">requested an alumni account.</p><small>
            <time class="media-meta text-muted">{{ $interval }}</time></small>
        </div>
    </div>
    </a>
@endforeach

resources/views/admin/partials/fnotis.blade.php
@if($fno == 0)
    <p class="notification-text font-small-3 text-muted text-xs-center" style="margin:20px">No new feedbacks</p>
@endif
@foreach($feedbacks as $f)
    <?php 
    $interval = \Carbon\Carbon::createFromTimeStamp(strtotime($f->created_at))->diffForHumans();
    ?>
    <a href="{{ route('feedbacks.show',$f->id) }}" class="list-group-item">
    <div class="media">
        <div class="media-left"><span class="avatar avatar-sm avatar-online rounded-circle"><img src="{{ asset('backend/app-assets/images/portrait/small/avatar-s-1.png') }}" alt="avatar"><i></i></span></div>
        <div class="media-body">
        <h6 class="media-heading">{{ $f->name }}</h6>
        <p class="notification-text font-small-3 text-muted" style="line-height:1.2em">Says "{{ $f->subject }}"</p><small>
            <time class="media-meta text-muted">{{ $interval }}</time></small>
        </div>
    </div>
    </a>
@endforeach

resources/views/admin/partials/footer.blade.php
 <footer class="footer footer-static footer-light navbar-border">
   
      <p class="clearfix text-muted text-sm-center mb-0 px-2"><span class="float-md-left d-xs-block d-md-inline-block">Copyright  &copy; 2017 <a href="https://themeforest.net/user/pixinvent/portfolio?ref=pixinvent" target="_blank" class="text-bold-800 grey darken-2">PIXINVENT </a>, All rights reserved. </span><span class="float-md-right d-xs-block d-md-inline-block">Hand-crafted & Made with <i class="icon-heart5 pink"></i></span></p>
    </footer>

    <!-- BEGIN VENDOR JS-->
    <script src="{{asset('backend/app-assets/js/core/libraries/jquery.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/vendors/js/ui/tether.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/js/core/libraries/bootstrap.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/vendors/js/ui/perfect-scrollbar.jquery.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/vendors/js/ui/unison.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/vendors/js/ui/blockUI.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/vendors/js/ui/jquery.matchHeight-min.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/vendors/js/ui/screenfull.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/vendors/js/extensions/pace.min.js')}}" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="{{asset('backend/app-assets/vendors/js/charts/chart.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN ROBUST JS-->
    <script src="{{asset('backend/app-assets/js/core/app-menu.js')}}" type="text/javascript"></script>
    <script src="{{asset('backend/app-assets/js/core/app.js')}}" type="text/javascript"></script>
    <!-- END ROBUST JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="{{asset('backend/app-assets/js/scripts/pages/dashboard-lite.js')}}" type="text/javascript"></script>
    <!-- END PAGE LEVEL JS-->
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.1.0/sweetalert2.all.js"></script>
    <script type="text/javascript">
  document.onreadystatechange = function () {
    var state = document.readyState
    if (state == 'interactive') {
        document.getElementById('contents').style.visibility="hidden";
    } else if (state == 'complete') {
      Pace.stop();
      
      setTimeout(function(){
          document.getElementById('interactive');
          document.getElementById('load').style.visibility="hidden";
          document.getElementById('contents').style.visibility="visible";
      },1000);
    }
  }
</script>
  <script>

    function getUnseenMsgCount(){
      Pace.ignore(function(){ 
        $.get("{{ route('getUnseenMsgCount') }}",
          function(data,status){
              $("#mno1" ).text(data.mno);  
          }
        );
      });
    }

    function getUnseenAlReqCount(){
      Pace.ignore(function(){ 
        $.get("{{ route('getUnseenAlReqCount') }}",
          function(data,status){
              $("#ano1" ).text(data.ano);  
          }
        );
      });
    }

    function getUnseenFeedbackCount(){
      Pace.ignore(function(){ 
        $.get("{{ route('getUnseenFeedbackCount') }}",
          function(data,status){
              $("#fno1" ).text(data.fno);  
          }
        );
      });
    }

    setInterval(function(){
        if("{{Auth::user()->roles()->where('title', '=', 'Contact Us Messages')->exists()}}"=='1')
          getUnseenMsgCount();
        if("{{Auth::user()->roles()->where('title', '=', 'Feedback Messages')->exists()}}"=='1')
          getUnseenFeedbackCount();
        if("{{Auth::user()->roles()->where('title', '=', 'Alumni Requests')->exists()}}"=='1')
          getUnseenAlReqCount();
        
    },60000);

    function getUnseenMsg(){
      $('#Mnotis').append('<div class="text-xs-center" style="margin:20px"><img src="{{ asset("loading1.gif") }}"/></div>');        
      $.get("{{ route('getUnseenMsg') }}",
        function(data,status){
            $("#mno1" ).text(data.mno);
            $("#mno2" ).text(data.mno+" New");

            $('#Mnotis').empty();
            $('#Mnotis').append(data.html);
            $('#Mnotis').perfectScrollbar('update');
        }
      ).fail(function() {
        location.reload();
      });
    }

    function getUnseenFeedback(){
      $('#Fnotis').append('<div class="text-xs-center" style="margin:20px"><img src="{{ asset("loading1.gif") }}"/></div>');        
      $.get("{{ route('getUnseenFeedbackMsg') }}",
        function(data,status){
            $("#fno1" ).text(data.fno);
            $("#fno2" ).text(data.fno+" New");

            $('#Fnotis').empty();
            $('#Fnotis').append(data.html);
            $('#Fnotis').perfectScrollbar('update');
        }
      ).fail(function() {
        location.reload();
      });
    }

    function getUnseenAlReq(){
      $('#Anotis').append('<div class="text-xs-center" style="margin:20px"><img src="{{ asset("loading1.gif") }}"/></div>');        
      $.get("{{ route('getUnseenAlReq') }}",
        function(data,status){
            $("#ano1" ).text(data.ano);
            $("#ano2" ).text(data.ano+" New");

            $('#Anotis').empty();
            $('#Anotis').append(data.html);
            $('#Anotis').perfectScrollbar('update');
        }
      ).fail(function() {
        location.reload();
      });
    }

    
  </script>

     @yield('js');
     
      
  </body>
</html>

resources/views/admin/partials/mnotis.blade.php
@if($mno == 0)
    <p class="notification-text font-small-3 text-muted text-xs-center" style="margin:20px">No new messages</p>
@endif
@foreach($messages as $m)
    <?php 
    $interval = \Carbon\Carbon::createFromTimeStamp(strtotime($m->created_at))->diffForHumans();
    ?>
    <a href="{{ route('contact-us-messages.show',$m->id) }}" class="list-group-item">
    <div class="media">
        <div class="media-left"><span class="avatar avatar-sm avatar-online rounded-circle"><img src="{{ asset('backend/app-assets/images/portrait/small/avatar-s-1.png') }}" alt="avatar"><i></i></span></div>
        <div class="media-body">
        <h6 class="media-heading">{{ $m->name }}</h6>
        <p class="notification-text font-small-3 text-muted" style="line-height:1.2em">Says "{{ $m->subject }}"</p><small>
            <time class="media-meta text-muted">{{ $interval }}</time></small>
        </div>
    </div>
    </a>
@endforeach

resources/views/admin/partials/sidebar.blade.php
<div data-scroll-to-active="true" class="main-menu menu-fixed menu-dark menu-accordion menu-shadow">
  <!-- main menu header-->
  
  <!-- / main menu header-->
  <!-- main menu content-->
  <div class="main-menu-content">
    <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">
        <li class=" nav-item @if(Request::is('admin/dashboard*')) active @endif">
          <a href="{{URL::to('/admin/dashboard')}}"><i class="icon-home3"></i><span data-i18n="nav.dash.main" class="menu-title">Home</span></a>
        </li>
          
        <li class="nav-item {{ Request::is('admin/staffs*')?'active':'' }}" {{Auth::user()->roles()->where('title', '=', 'Staffs')->exists() ? '':'hidden'}}><a href="{{ route('staffs.index') }}"><i class="icon-android-contacts"></i><span data-i18n="nav.staffs.main" class="menu-title">Staffs</span></a>
        </li>

        <li class="nav-item @if(Request::is('admin/notice*'))
                active
                @endif" {{Auth::user()->roles()->where('title', '=', 'Notices')->exists() ? '':'hidden'}}><a href="{{URL::to('/admin/notice')}}"><i class="fa fa-bell" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Notices</span>
          </a></li>      
              
        <li class=" nav-item @if(Request::is('admin/downloads*'))
                  active
                  @endif" {{Auth::user()->roles()->where('title', '=', 'Downloads')->exists() ? '':'hidden'}}><a href={{URL::to('/admin/downloads')}}><i class="icon-download"></i><span data-i18n="nav.dash.main" class="menu-title">Downloads</span>
      
          </a></li>
          <li class=" nav-item @if(Request::is('admin/resources*') || Request::is('admin/materials*') )
                    active
                    @endif" {{Auth::user()->roles()->where('title', '=', 'Resources')->exists() ? '':'hidden'}}><a href={{URL::to('/admin/resources')}}><i class="fa fa-sticky-note-o" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Resources</span>
        
          </a></li>
          <li class=" nav-item @if(Request::is('admin/gallery*'))
                    active
                    @endif" {{Auth::user()->roles()->where('title', '=', 'Gallery')->exists() ? '':'hidden'}}><a href={{URL::to('/admin/gallery')}}><i class="fa fa-picture-o" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Gallery</span> </a></li>
          <li class=" nav-item @if(Request::is('admin/testimonials*'))
                    active
                    @endif" {{Auth::user()->roles()->where('title', '=', 'Testimonials')->exists() ? '':'hidden'}}><a href={{URL::to('/admin/testimonials')}}><i class="fa fa-quote-left" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Testimonials</span> </a></li>
          
          <li class=" nav-item @if(Request::is('admin/teachers*'))
                      active
                      @endif" {{Auth::user()->roles()->where('title', '=', 'Teachers')->exists() ? '':'hidden'}}><a href={{URL::to('/admin/teachers')}}><i class="fa fa-user" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Teachers</span> </a></li>

          <li class=" nav-item @if(Request::is('admin/events*'))
                        active
                        @endif" {{Auth::user()->roles()->where('title', '=', 'Event Settings')->exists() ? '':'hidden'}}><a href="{{route('admin.events')}}"><i class="fa fa-calendar" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Event Settings</span></a></li>
          <li class="nav-item {{ Request::is('admin/calender*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'Calendar')->exists() ? '':'hidden'}}><a href="{{route('calender.index')}}"><i class="fa fa-calendar" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Calendar</span></a></li>

          <li class="nav-item {{ Request::is('admin/faqs*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'FAQs')->exists() ? '':'hidden'}}><a href="{{route('admin.faqs')}}"><i class="fa fa-question" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">FAQs</span></a></li>

          <li class="nav-item {{ Request::is('admin/activities*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'Activities')->exists() ? '':'hidden'}}><a href="{{route('admin.activities')}}"><i class="fa fa-tasks" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Activities</span></a></li>

          <li class="nav-item {{ Request::is('admin/alumni_requests*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'Alumni Requests')->exists() ? '':'hidden'}}><a href="{{route('alumni_requests.index')}}"><i class="fa fa-user"><i class="fa fa-clock-o" style="font-size: 11px;vertical-align: top;"></i></i><span data-i18n="nav.dash.main" class="menu-title">Alumni Requests</span></a></li>

          <li class="nav-item {{ Request::is('admin/alumni_photos*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'Alumni Photos')->exists() ? '':'hidden'}}><a href="{{route('alumni_photos.index')}}"><i class="fa fa-user"><i class="fa fa-picture-o" style="font-size: 11px;vertical-align: top;"></i></i><span data-i18n="nav.dash.main" class="menu-title">Alumni Photos</span></a></li>
          
          <li class="nav-item {{ Request::is('admin/advertises*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'Advertisements')->exists() ? '':'hidden'}}><a href="{{route('admin.advertises')}}"><i class="fa fa-tasks" aria-hidden="true"></i><span data-i18n="nav.dash.main" class="menu-title">Advertisements</span></a></li>

          <li class="nav-item {{ Request::is('admin/contact-us-messages*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'Contact Us Messages')->exists() ? '':'hidden'}}><a href="{{ route('contact-us-messages.index') }}"><i class="icon-at2"></i><span data-i18n="nav.contact-us-messages.main" class="menu-title">Contact Us Messages</span></a>
          </li>

          <li class="nav-item {{ Request::is('admin/feedbacks*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'Feedback Messages')->exists() ? '':'hidden'}}><a href="{{ route('feedbacks.index') }}"><i class="fa fa-comments"></i><span data-i18n="nav.feedbacks.main" class="menu-title">Feedbacks Messages</span></a>
          </li>
          
          <li class="nav-item {{ Request::is('admin/newsletter*') ? 'active' : '' }}" {{Auth::user()->roles()->where('title', '=', 'Newsletter')->exists() ? '':'hidden'}}><a href="{{ route('newsletter') }}"><i class="icon-mail6"></i><span data-i18n="nav.newsletter.main" class="menu-title">Newsletter</span></a>
          </li>
          
        </ul>
  </div>
  <!-- /main menu content-->
  <!-- main menu footer-->
  <!-- include includes/menu-footer-->
  <!-- main menu footer-->
</div>